// Blacklist des domaines d'email temporaires et autres emails non autorisés
// Ce fichier contient une liste des domaines connus pour fournir des adresses email temporaires
export const tempEmailDomains = [
  // Services populaires d'email temporaire
  '10minutemail.com',
  '10minutemail.net',
  '20minutemail.com',
  '2prong.com',
  '30minutemail.com',
  '3d-painting.com',
  '7-mail.com',
  'anonbox.net',
  'armyspy.com',
  'bccto.me',
  'binkmail.com',
  'bit-company.com',
  'bloatbox.com',
  'bobmail.info',
  'breakthru.com',
  'brefmail.com',
  'bumpymail.com',
  'byom.de',
  'chammy.info',
  'childsavetrust.org',
  'chogmail.com',
  'cool.fr.nf',
  'correo.blogos.net',
  'crazymailing.com',
  'cuvox.de',
  'dacoolest.com',
  'dandikmail.com',
  'dayrep.com',
  'deadaddress.com',
  'despam.it',
  'dispostable.com',
  'dodgeit.com',
  'dodgit.com',
  'dontreg.com',
  'dontsendmespam.de',
  'drdrb.com',
  'dump-email.info',
  'dumpandjunk.com',
  'dumpmail.de',
  'dumpyemail.com',
  'e4ward.com',
  'einrot.com',
  'emailfake.com',
  'emailias.com',
  'emailinfive.com',
  'emailisvalid.com',
  'emailmiser.com',
  'emailsensei.com',
  'emailtemporar.ro',
  'emailtemporario.com.br',
  'emailto.de',
  'emailwarden.com',
  'emailxfer.com',
  'emz.net',
  'enterto.com',
  'ephemail.net',
  'explodemail.com',
  'fakeinbox.com',
  'fakemail.fr',
  'fansworldwide.de',
  'fantasymail.de',
  'fastacura.com',
  'fastchevy.com',
  'fastchrysler.com',
  'fastkawasaki.com',
  'fastmazda.com',
  'fastmitsubishi.com',
  'fastnissan.com',
  'fastsubaru.com',
  'fastsuzuki.com',
  'fasttoyota.com',
  'fastyamaha.com',
  'fillmail.info',
  'fleckens.hu',
  'frozenscythe.com',
  'garbagemail.org',
  'get-mail.info',
  'getairmail.com',
  'getmails.eu',
  'ghosttexter.de',
  'girlsunderthehood.com',
  'great-host.in',
  'guerillamail.com',
  'guerillamail.net',
  'guerillamail.org',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'gustr.com',
  'h.mintemail.com',
  'haltospam.com',
  'hatespam.org',
  'hidemail.de',
  'hidzz.com',
  'hmamail.com',
  'incognitomail.com',
  'incognitomail.net',
  'incognitomail.org',
  'insorg-mail.info',
  'instant-mail.de',
  'ipoo.org',
  'irish2me.com',
  'iwi.net',
  'jetable.com',
  'jetable.fr.nf',
  'jetable.net',
  'jetable.org',
  'jnxjn.com',
  'junkmail.ga',
  'kasmail.com',
  'kaspop.com',
  'keepmymail.com',
  'killmail.com',
  'killmail.net',
  'klzlk.com',
  'kook.ml',
  'kurzepost.de',
  'letthemeatspam.com',
  'lhsdv.com',
  'lifebyfood.com',
  'link2mail.net',
  'litedrop.com',
  'loadby.us',
  'lookugly.com',
  'lopl.co.cc',
  'lortemail.dk',
  'lr78.com',
  'lroid.com',
  'lukop.dk',
  'mail.by',
  'mail.mezimages.net',
  'mail4trash.com',
  'mailbidon.com',
  'mailbiz.biz',
  'mailblocks.com',
  'mailcatch.com',
  'maildrop.cc',
  'maileater.com',
  'mailexpire.com',
  'mailfree.ga',
  'mailfreeonline.com',
  'mailguard.me',
  'mailin8r.com',
  'mailinatar.com',
  'mailinater.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator2.com',
  'mailincubator.com',
  'mailmetrash.com',
  'mailnator.com',
  'mailnesia.com',
  'mailnull.com',
  'mailsac.com',
  'mailscrap.com',
  'mailshell.com',
  'mailsiphon.com',
  'mailtemp.info',
  'mailtome.de',
  'mailtothis.com',
  'mailtrash.net',
  'mailtv.net',
  'mailtv.tv',
  'mailzilla.com',
  'mailzilla.org',
  'makemetheking.com',
  'manybrain.com',
  'mbx.cc',
  'mega.zik.dj',
  'meinspamschutz.de',
  'meltmail.com',
  'messagebeamer.de',
  'mierdamail.com',
  'mintemail.com',
  'mjukglass.nu',
  'mobi.web.id',
  'moburl.com',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'monumentmail.com',
  'msa.minsmail.com',
  'mt2009.com',
  'mt2014.com',
  'mypartyclip.de',
  'myphantomemail.com',
  'myspamless.com',
  'mytemp.email',
  'mytrashmail.com',
  'natemails.info',
  'nepwk.com',
  'nervmich.net',
  'nervtmich.net',
  'netmails.com',
  'netmails.net',
  'netzidiot.de',
  'neverbox.com',
  'no-spam.ws',
  'nobulk.com',
  'noclickemail.com',
  'nogmailspam.info',
  'nomail.xl.cx',
  'nomail2me.com',
  'nomorespamemails.com',
  'nonspam.eu',
  'nonspammer.de',
  'noref.in',
  'nospam.ze.tc',
  'nospam4.us',
  'nospamfor.us',
  'nospamthanks.info',
  'notmailinator.com',
  'nowmymail.com',
  'nurfuerspam.de',
  'nus.edu.sg',
  'objectmail.com',
  'obobbo.com',
  'odnorazovoe.ru',
  'oneoffemail.com',
  'onewaymail.com',
  'online.ms',
  'opayq.com',
  'ordinaryamerican.net',
  'ourklips.com',
  'outlawspam.com',
  'ovpn.to',
  'owlpic.com',
  'pancakemail.com',
  'pcusers.otherinbox.com',
  'pjkls.com',
  'plexolan.de',
  'pookmail.com',
  'proxymail.eu',
  'prtnx.com',
  'putthisinyourspamdatabase.com',
  'qq.com',
  'quickinbox.com',
  'rcpt.at',
  'recode.me',
  'recursor.net',
  'regbypass.com',
  'rejectmail.com',
  'remail.cf',
  'remail.ga',
  'rhyta.com',
  'rklips.com',
  'rmqkr.net',
  'safe-mail.net',
  'safetymail.info',
  'safetypost.de',
  'sandelf.de',
  'saynotospams.com',
  'schafmail.de',
  'schrott-email.de',
  'secretemail.de',
  'secure-mail.biz',
  'selfdestructingmail.com',
  'sendspamhere.de',
  'sharklasers.com',
  'shieldedmail.com',
  'shitmail.me',
  'shitware.nl',
  'shmeriously.com',
  'shortmail.net',
  'sibmail.com',
  'sinnlos-mail.de',
  'siteposter.net',
  'skeefmail.com',
  'slopsbox.com',
  'slushmail.com',
  'smashmail.de',
  'smellfear.com',
  'snakemail.com',
  'sneakemail.com',
  'snkmail.com',
  'sofimail.com',
  'sofort-mail.de',
  'sogetthis.com',
  'soodonims.com',
  'spam.la',
  'spamail.de',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'spambox.info',
  'spambox.irishspringtours.com',
  'spambox.us',
  'spamcannon.com',
  'spamcannon.net',
  'spamcon.org',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamcowboy.net',
  'spamcowboy.org',
  'spamday.com',
  'spamex.com',
  'spamfree24.com',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.info',
  'spamfree24.net',
  'spamfree24.org',
  'spamgoes.com',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spamkill.info',
  'spaml.com',
  'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spamoff.de',
  'spamslicer.com',
  'spamspot.com',
  'spamstack.net',
  'spamthis.co.uk',
  'spamthisplease.com',
  'spamtrail.com',
  'spamtroll.net',
  'speed.1s.fr',
  'squizzy.de',
  'ssoia.com',
  'startkeys.com',
  'stinkefinger.net',
  'stop-my-spam.com',
  'stuffmail.de',
  'super-auswahl.de',
  'supergreatmail.com',
  'supermailer.jp',
  'superplatyna.com',
  'suremail.info',
  'tagyourself.com',
  'teewars.org',
  'teleworm.com',
  'teleworm.us',
  'temp-mail.org',
  'temp-mail.ru',
  'tempalias.com',
  'tempe-mail.com',
  'tempemail.biz',
  'tempemail.com',
  'tempemail.net',
  'tempinbox.co.uk',
  'tempinbox.com',
  'tempmail.eu',
  'tempmail2.com',
  'tempmaildemo.com',
  'tempmailer.com',
  'tempmailer.de',
  'tempmailaddress.com',
  'tempthe.net',
  'thankyou2010.com',
  'thc.st',
  'thelimestones.com',
  'thisisnotmyrealemail.com',
  'thismail.net',
  'throwam.com',
  'throwawayemailaddresses.com',
  'tilien.com',
  'tittbit.in',
  'tizi.com',
  'tmailinator.com',
  'tradermail.info',
  'trash-amil.com',
  'trash-mail.at',
  'trash-mail.com',
  'trash-mail.de',
  'trash2009.com',
  'trashdevil.com',
  'trashdevil.de',
  'trashemail.de',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmail.ws',
  'trashmailer.com',
  'trashymail.com',
  'trialmail.de',
  'trillianpro.com',
  'tryalert.com',
  'turual.com',
  'twinmail.de',
  'tyldd.com',
  'uggsrock.com',
  'umail.net',
  'upliftnow.com',
  'uplipht.com',
  'uroid.com',
  'us.af',
  'venompen.com',
  'veryrealemail.com',
  'viditag.com',
  'viewcastmedia.com',
  'viewcastmedia.net',
  'viewcastmedia.org',
  'vomoto.com',
  'vubby.com',
  'walala.org',
  'walkmail.net',
  'webemail.me',
  'webm4il.info',
  'wegwerfadresse.de',
  'wegwerfemail.de',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wh4f.org',
  'whyspam.me',
  'willselfdestruct.com',
  'winemaven.info',
  'wronghead.com',
  'www.e4ward.com',
  'www.gishpuppy.com',
  'www.mailinator.com',
  'wwwnew.eu',
  'x.ip6.li',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'yapped.net',
  'yeah.net',
  'yep.it',
  'yogamaven.com',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'yourdomain.com',
  'ypmail.webredirect.org',
  'yuurok.com',
  'zehnminutenmail.de',
  'zippymail.info',
  'zoaxe.com',
  'zoemail.org',
  
  // Services plus récents d'email temporaire
  'tempail.com',
  'temp-mail.io',
  'temporarymail.com',
  'throwaway.email',
  'burnermail.io',
  'discard.email',
  'emailondeck.com',
  'fakemailgenerator.com',
  'generator.email',
  'gmailnator.com',
  'inboxkitten.com',
  'mohmal.com',
  'smailpro.com',
  'tempmailo.com',
  'tempr.email',
  '10mail.org',
  '33mail.com',
  'deadfake.cf',
  'emailfake.ml',
  'fakemail.net',
  'getairmail.cf',
  'mailinator.gq',
  'mailsac.com',
  'maildrop.gq',
  'tempmailgen.com',
  'tempmail.ninja',
  'yopmail.gq',
  'guerrillamail.biz',
  'sharklasers.com',
  'grr.la',
  'guerrillamail.info',
  'pokemail.net',
  'spam4.me',
  'trbvm.com',
  'byom.de',
  'fudgerub.com',
  'lookugly.com',
  'smellfear.com',
  
  // Domaines .tk, .ml, .ga, .cf suspects souvent utilisés
  'email.tk',
  'mail.tk',
  'temp.tk',
  'email.ml',
  'mail.ml',
  'temp.ml',
  'email.ga',
  'mail.ga',
  'temp.ga',
  'email.cf',
  'mail.cf',
  'temp.cf',
  
  // Autres services connus
  'mailforspam.com',
  'tempemail.co',
  'temporary-mail.net',
  'tmpmail.net',
  'tmpmail.org',
  'tmpnator.live',
  'guerillamail.net',
  'guerillamail.org',
  'guerillamail.biz',
  'sharklasers.com',
  'grr.la',
  'guerrillamail.info',
  'pokemail.net',
  'spam4.me',
  'trbvm.com',
  'byom.de',
  'fudgerub.com',
  'lookugly.com',
  'smellfear.com',
  
  // Ajoutez ici d'autres domaines selon vos besoins
  // Cette liste peut être mise à jour régulièrement
];

// Domaines de test et génériques à bloquer
export const testDomains = [
  'example.com',
  'example.org',
  'example.net',
  'test.com',
  'test.org',
  'test.net',
  'domain.com',
  'domain.org',
  'domain.net',
  'localhost',
  'local',
  'invalid',
  'dummy.com',
  'fake.com',
  'sample.com',
  'placeholder.com'
];

// Ancien domaine Gmail à bloquer  
export const deprecatedGmailDomains = [
  'googlemail.com',
  'googlemail.co.uk',
  'googlemail.de',
  'googlemail.fr'
];

// Fonction pour détecter les alias Gmail avec "+"
export const hasGmailAlias = (email) => {
  if (!email || typeof email !== 'string') return false;
  
  const [localPart, domain] = email.split('@');
  if (!localPart || !domain) return false;
  
  // Vérifier si c'est un domaine Gmail et contient un "+"
  const gmailDomains = ['gmail.com', 'googlemail.com'];
  const isGmailDomain = gmailDomains.includes(domain.toLowerCase());
  
  return isGmailDomain && localPart.includes('+');
};

// Fonction pour détecter les emails Gmail avec trop de points
export const hasExcessiveGmailDots = (email) => {
  if (!email || typeof email !== 'string') return false;
  
  const [localPart, domain] = email.split('@');
  if (!localPart || !domain) return false;
  
  // Vérifier si c'est un domaine Gmail
  const gmailDomains = ['gmail.com', 'googlemail.com'];
  const isGmailDomain = gmailDomains.includes(domain.toLowerCase());
  
  if (!isGmailDomain) return false;
  
  // Compter les points dans la partie locale
  const dotCount = (localPart.match(/\./g) || []).length;
  
  // Considérer comme suspect si plus de 3 points
  // ou si le ratio points/caractères est trop élevé
  const suspiciousPattern = dotCount > 3 || (dotCount / localPart.length) > 0.3;
  
  return suspiciousPattern;
};

// Fonction principale pour vérifier si un email doit être refusé
export const isEmailBlocked = (email) => {
  if (!email || typeof email !== 'string') return { blocked: true, reason: 'Email invalide' };
  
  const domain = email.split('@')[1]?.toLowerCase().trim();
  if (!domain) return { blocked: true, reason: 'Format email invalide' };
  
  // Vérifier les domaines temporaires
  if (tempEmailDomains.includes(domain)) {
    return { blocked: true, reason: 'Les adresses email temporaires ne sont pas autorisées' };
  }
  
  // Vérifier les domaines de test
  if (testDomains.includes(domain)) {
    return { blocked: true, reason: 'Les domaines de test ne sont pas autorisés' };
  }
  
  // Vérifier les anciens domaines Gmail
  if (deprecatedGmailDomains.includes(domain)) {
    return { blocked: true, reason: 'Veuillez utiliser une adresse @gmail.com' };
  }
  
  // Vérifier les alias Gmail avec "+"
  if (hasGmailAlias(email)) {
    return { blocked: true, reason: 'Les alias Gmail avec "+" ne sont pas autorisés' };
  }
  
  // Vérifier les Gmail avec trop de points
  if (hasExcessiveGmailDots(email)) {
    return { blocked: true, reason: 'Cette adresse Gmail semble suspecte' };
  }
  
  return { blocked: false, reason: null };
};

// Fonction utilitaire pour vérifier si un email utilise un domaine temporaire (DEPRECATED)
// Utilisez isEmailBlocked() à la place
export const isTemporaryEmail = (email) => {
  console.warn('isTemporaryEmail() est déprécié, utilisez isEmailBlocked() à la place');
  const result = isEmailBlocked(email);
  return result.blocked;
};

// Fonction pour ajouter de nouveaux domaines à la blacklist (utile pour les mises à jour)
export const addToBlacklist = (domains) => {
  if (Array.isArray(domains)) {
    domains.forEach(domain => {
      const normalizedDomain = domain.toLowerCase().trim();
      if (!tempEmailDomains.includes(normalizedDomain)) {
        tempEmailDomains.push(normalizedDomain);
      }
    });
  } else if (typeof domains === 'string') {
    const normalizedDomain = domains.toLowerCase().trim();
    if (!tempEmailDomains.includes(normalizedDomain)) {
      tempEmailDomains.push(normalizedDomain);
    }
  }
};

// Fonction pour obtenir le nombre total de domaines dans la blacklist
export const getBlacklistSize = () => tempEmailDomains.length;

// Fonction pour rechercher des domaines dans la blacklist
export const searchInBlacklist = (searchTerm) => {
  if (!searchTerm || typeof searchTerm !== 'string') return [];
  
  const term = searchTerm.toLowerCase();
  return tempEmailDomains.filter(domain => domain.includes(term));
};
